import type { AssetProvenance, PixelAssetManifest } from "@pixelaid/shared";
import type { EngineExportBundle, EngineExportWarning } from "./engineTypes";
import { collectCommonEngineWarnings } from "./engineWarnings";
import { collectTilesetDimensionWarnings } from "./tiled";

export type LdtkTilesetCompanion = {
  identifier: string;
  relPath: string;
  tileGridSize: number;
  pxWid: number;
  pxHei: number;
  spacing: number;
  padding: number;
  pixelAid: {
    app: string;
    version: string;
    assetType: string;
    tileWidth: number;
    tileHeight: number;
    columns: number;
    tileCount: number;
    palette: string[];
    source: { width: number; height: number };
    gridConfidence: number;
    provenance?: Pick<AssetProvenance, "origin" | "provider" | "model">;
    notes: string[];
  };
};

export type LdtkTilesetOptions = {
  imageFile?: string;
  identifier?: string;
};

export function createLdtkTilesetExport(
  manifest: PixelAssetManifest,
  options: LdtkTilesetOptions = {}
): EngineExportBundle {
  const imageFile = options.imageFile ?? manifest.meta.image;
  const identifier = options.identifier ?? toLdtkIdentifier(stripImageExtension(baseFileName(imageFile)));

  return {
    files: [
      {
        path: `ldtk/${identifier}.ldtk-tileset.json`,
        kind: "json",
        contents: createLdtkTilesetCompanion(manifest, { imageFile, identifier })
      },
      {
        path: "ldtk/README.md",
        kind: "text",
        contents: createLdtkReadme(imageFile, identifier)
      }
    ],
    warnings: createLdtkWarnings(manifest)
  };
}

export function createLdtkTilesetCompanion(
  manifest: PixelAssetManifest,
  options: LdtkTilesetOptions = {}
): LdtkTilesetCompanion {
  const imageFile = options.imageFile ?? manifest.meta.image;
  const identifier = options.identifier ?? toLdtkIdentifier(stripImageExtension(baseFileName(imageFile)));

  return {
    identifier,
    relPath: imageFile,
    tileGridSize: manifest.sheet.frameWidth,
    pxWid: manifest.sheet.width,
    pxHei: manifest.sheet.height,
    spacing: manifest.sheet.spacing,
    padding: manifest.sheet.margin,
    pixelAid: {
      app: manifest.meta.app,
      version: manifest.meta.version,
      assetType: manifest.meta.assetType,
      tileWidth: manifest.sheet.frameWidth,
      tileHeight: manifest.sheet.frameHeight,
      columns: calculateColumns(manifest),
      tileCount: manifest.frames.length,
      palette: [...manifest.meta.palette],
      source: { ...manifest.meta.source },
      gridConfidence: manifest.meta.operation.grid.confidence,
      ...(manifest.meta.provenance ? { provenance: createProvenanceBlock(manifest.meta.provenance) } : {}),
      notes: [
        "LDtk project files are not generated by this adapter; create or select a project tileset and copy these values.",
        "PixelAid manifest remains authoritative for export diagnostics and future map data."
      ]
    }
  };
}

function createLdtkWarnings(manifest: PixelAssetManifest): EngineExportWarning[] {
  const warnings = [...collectCommonEngineWarnings(manifest, "ldtk")];

  if (manifest.sheet.frameWidth !== manifest.sheet.frameHeight) {
    warnings.push({
      target: "ldtk",
      code: "engine-ldtk-square-grid-size-required",
      severity: "warning",
      message:
        "LDtk tilesets use one tileGridSize value; non-square PixelAid tiles should be manually reviewed during LDtk import."
    });
  }

  warnings.push(...collectTilesetDimensionWarnings(manifest, "ldtk"));
  return warnings;
}

function createProvenanceBlock(provenance: AssetProvenance): Pick<AssetProvenance, "origin" | "provider" | "model"> {
  return {
    origin: provenance.origin,
    ...(provenance.provider ? { provider: provenance.provider } : {}),
    ...(provenance.model ? { model: provenance.model } : {})
  };
}

function calculateColumns(manifest: PixelAssetManifest): number {
  const tileWidth = manifest.sheet.frameWidth;
  const usableWidth = manifest.sheet.width - manifest.sheet.margin * 2;
  if (tileWidth < 1 || usableWidth < tileWidth) {
    return 0;
  }
  return Math.floor((usableWidth + manifest.sheet.spacing) / (tileWidth + manifest.sheet.spacing));
}

function createLdtkReadme(imageFile: string, identifier: string): string {
  return [
    "# LDtk Tileset Companion",
    "",
    `Image: \`${imageFile}\``,
    `Companion JSON: \`ldtk/${identifier}.ldtk-tileset.json\``,
    "",
    "- LDtk project files are not generated yet; import or create the tileset manually in LDtk.",
    "- Copy identifier, tileGridSize, image size, spacing, and padding from the companion JSON.",
    "- LDtk uses square tile grid sizing, so review non-square PixelAid tiles before authoring maps.",
    "- Keep the generic PixelAid manifest with this companion for palette, provenance, and diagnostics.",
    ""
  ].join("\n");
}

function toLdtkIdentifier(value: string): string {
  const identifier = value.replace(/[^A-Za-z0-9_]/g, "_").replace(/^([0-9])/, "_$1");
  return identifier.length > 0 ? identifier : "tileset";
}

function baseFileName(path: string): string {
  const normalized = path.replace(/\\/g, "/");
  const fileName = normalized.split("/").filter(Boolean).at(-1);
  return fileName && fileName.length > 0 ? fileName : "tileset";
}

function stripImageExtension(fileName: string): string {
  const withoutExtension = fileName.replace(/\.[^.]+$/, "");
  return withoutExtension.length > 0 ? withoutExtension : "tileset";
}
