import { describe, expect, test } from "vitest";
import type { PixelAssetManifest } from "@pixelaid/shared";
import { createLdtkTilesetCompanion, createLdtkTilesetExport } from "./ldtk";

describe("LDtk tileset companion export adapter", () => {
  test("creates practical tileset-definition companion JSON for manual LDtk import", () => {
    const companion = createLdtkTilesetCompanion(createTilesetManifest());

    expect(companion).toEqual({
      identifier: "terrain_tiles",
      relPath: "terrain_tiles.png",
      tileGridSize: 16,
      pxWid: 54,
      pxHei: 36,
      spacing: 2,
      padding: 1,
      pixelAid: {
        app: "PixelAid",
        version: "0.1.0",
        assetType: "tileSheet",
        tileWidth: 16,
        tileHeight: 16,
        columns: 3,
        tileCount: 6,
        palette: ["#000000", "#4b692f", "#9bbc0f"],
        source: { width: 220, height: 144 },
        gridConfidence: 0.98,
        provenance: {
          origin: "generated",
          provider: "fixture-ai",
          model: "tiles-v1"
        },
        notes: [
          "LDtk project files are not generated by this adapter; create or select a project tileset and copy these values.",
          "PixelAid manifest remains authoritative for export diagnostics and future map data."
        ]
      }
    });
  });

  test("exports companion files and warns when LDtk square grid size cannot represent tile dimensions exactly", () => {
    const manifest = createTilesetManifest();
    manifest.sheet.frameHeight = 12;

    const result = createLdtkTilesetExport(manifest);
    const readme = result.files.find((file) => file.path === "ldtk/README.md");

    expect(result.files.map((file) => file.path)).toEqual(["ldtk/terrain_tiles.ldtk-tileset.json", "ldtk/README.md"]);
    expect(readme).toEqual(expect.objectContaining({ kind: "text", contents: expect.stringContaining("manual") }));
    expect(result.warnings.map((warning) => warning.code)).toEqual([
      "engine-ldtk-square-grid-size-required",
      "engine-ldtk-sheet-height-misaligned",
      "engine-ldtk-frame-size-mismatch"
    ]);
  });
});

function createTilesetManifest(): PixelAssetManifest {
  return {
    meta: {
      app: "PixelAid",
      version: "0.1.0",
      image: "terrain_tiles.png",
      assetType: "tileSheet",
      palette: ["#000000", "#4b692f", "#9bbc0f"],
      provenance: {
        origin: "generated",
        provider: "fixture-ai",
        model: "tiles-v1"
      },
      source: { width: 220, height: 144 },
      operation: {
        settings: {
          mode: "tileSheet",
          assetType: "tileSheet",
          maxColors: 16,
          grid: { detect: "manual", scale: 4 },
          downscale: "dominant",
          alpha: "preserve",
          cleanup: { removeOrphans: false, jaggyCleanup: false, preserveSinglePixelDetails: true }
        },
        grid: {
          outputWidth: 54,
          outputHeight: 36,
          scaleX: 4,
          scaleY: 4,
          phaseX: 0,
          phaseY: 0,
          confidence: 0.98,
          reason: "test"
        },
        durationMs: 3
      }
    },
    sheet: { width: 54, height: 36, frameWidth: 16, frameHeight: 16, margin: 1, spacing: 2, extrude: 0 },
    frames: [
      { name: "grass", rect: { x: 1, y: 1, w: 16, h: 16 }, pivot: { x: 8, y: 16 }, durationMs: 120 },
      { name: "water", rect: { x: 19, y: 1, w: 16, h: 16 }, pivot: { x: 8, y: 16 }, durationMs: 120 },
      { name: "stone", rect: { x: 37, y: 1, w: 16, h: 16 }, pivot: { x: 8, y: 16 }, durationMs: 120 },
      { name: "dirt", rect: { x: 1, y: 19, w: 16, h: 16 }, pivot: { x: 8, y: 16 }, durationMs: 120 },
      { name: "sand", rect: { x: 19, y: 19, w: 16, h: 16 }, pivot: { x: 8, y: 16 }, durationMs: 120 },
      { name: "edge", rect: { x: 37, y: 19, w: 16, h: 16 }, pivot: { x: 8, y: 16 }, durationMs: 120 }
    ],
    animations: {}
  };
}
