export const PIXELAID_APP_NAME = "PixelAid";
export const PIXELAID_VERSION = "0.1.0";

export type {
  AlphaMode,
  AlphaCleanupDiagnostics,
  AlphaCleanupSettings,
  AnimationTag,
  AssetMode,
  AssetProvenance,
  AssetProvenanceOrigin,
  AssetProvenanceSettingValue,
  AssetType,
  AssetTypeClassification,
  AssetTypeSupport,
  AssetTypeWarning,
  ContrastExpansionDiagnostics,
  ContrastExpansionSettings,
  DiagnosticSeverity,
  DownscaleMethod,
  FixMetrics,
  FixOptions,
  FixPhaseTiming,
  FixPhaseTimingName,
  FrameStabilityDiagnostics,
  FrameStabilityIssue,
  FrameStabilityIssueCode,
  FrameStabilityMetric,
  FrameStabilitySeverity,
  GridCandidate,
  GridCandidateDiagnostics,
  GridDriftDiagnostics,
  GridSobelTileVotingDiagnostics,
  HaloRemovalDiagnostics,
  MorphologyCleanupSettings,
  MorphologyDiagnostics,
  OutlineCleanupDiagnostics,
  OutlineMode,
  PaletteDiagnostics,
  PaletteDitheringMode,
  PaletteDitheringRisk,
  PaletteDitheringSafetyDiagnostics,
  PaletteDriftDiagnostics,
  PaletteLockScope,
  PaletteMode,
  PaletteSettings,
  PaletteStabilityLabel,
  PaletteStrategy,
  Pivot,
  PixelAssetManifest,
  PixelFixDiagnostics,
  PixelFixResult,
  Rect,
  RGBAImage,
  SceneAssetDiagnostics,
  SheetConfidenceDetail,
  SheetConfidenceLabel,
  SheetConditioningDiagnostics,
  SheetConditioningIssue,
  SheetConditioningIssueCode,
  SheetFrameLayoutOverride,
  SheetLayoutConfidenceModel,
  SheetLayoutDetection,
  SheetLayoutDiagnostics,
  SheetLayoutOverrideScope,
  SheetRowConfidenceExplanation,
  SheetRowLabel,
  SheetSliceOptions,
  SpriteAnimation,
  SpriteFrameAnchor,
  SpriteFrameBox,
  SpriteFrameBoxType,
  SpriteFrame,
  TilemapDiagnostics,
  TilemapCanonicalTile,
  TilemapExportMetadata,
  TilemapGridCandidate,
  TilemapLayerMetadata,
  TilemapWorkflowStatus,
  TilemapWorkflowWarning,
  TilemapWorkflowWarningCode,
  TilesetSeamDiagnostics,
  TilesetSeamEdge,
  TilesetSeamIssue,
  TilesetSeamIssueCode,
  TilesetSeamRepairApplication,
  TilesetSeamRepairDiagnostics,
  TilesetSeamRepairSkipped,
  TilesetSeamRepairStrategy,
  TilesetSeamRepairSuggestion,
  TransferableImage,
  WorkerProgress,
  WorkerProgressStage
} from "./types";

export { assetTypeDefinitions, assetTypeToMode, getAssetTypeDefinition } from "./assetTypes";
export type { AssetTypeDefinition } from "./assetTypes";
export { getAssetTypeCleanupPreset, getAssetTypeWarnings } from "./assetTypePresets";
export type { AssetTypeCleanupPreset } from "./assetTypePresets";
