export {
  decodePngFile,
  encodePngFile,
  readRgbaImageFile,
  type ImageFileMetadata,
} from "./imageIo";
export {
  normalizeFixOptions,
  parseAutomationAssetType,
  type AutomationAssetTypeInput,
  type AutomationFixOptionsInput,
  type AutomationTargetInput,
  type ParsedAutomationAssetType,
} from "./options";
export {
  assertSafeBundlePath,
  planOutputFile,
  relativeToDirectory,
  writeJsonOutput,
  writeTextOutput,
  type PlanOutputFileOptions,
  type PlannedOutputFile,
} from "./paths";
export {
  exportEngineBundle,
  extractPaletteFile,
  fixSprite,
  fixSpriteSheet,
  createQualityReport,
  inspectImage,
  suggestFixSettings,
  type AutomationFileRecord,
  type CreateQualityReportRequest,
  type ExportEngineBundleRequest,
  type ExtractPaletteFileRequest,
  type FixOperationResult,
  type FixSpriteRequest,
  type FixSpriteSheetRequest,
  type FixSuggestion,
  type ImageInspection,
  type InspectImageRequest,
  type QualityReportAsset,
  type QualityReportAssetRequest,
  type QualityReportBatch,
  type SuggestFixSettingsRequest,
} from "./operations";
export {
  automationError,
  automationOk,
  unknownAutomationError,
  type AutomationError,
  type AutomationErrorCode,
  type AutomationExitCode,
  type AutomationFailure,
  type AutomationResult,
  type AutomationSuccess,
} from "./result";
