import { describe, expect, test } from "vitest";
import {
  benchmarkFixtureCatalog,
  cleanupFixtureCatalog,
  cleanupFixtureCategories,
  qualityFixtureFailureCategories,
  qualityFailureFixtureCatalog,
  qualityFixtureReviewStatuses,
  validateQualityFixtureMetadata,
  visualRegressionCases
} from "./index";
import { assetTypeDefinitions } from "@pixelaid/shared";

const expectedCategories = [
  "highResolutionPseudoPixelSprite",
  "transparentMatteHaloSprite",
  "paletteDriftAnimationFrames",
  "unevenSpriteSheet",
  "presentationSpriteSheet",
  "tilesetSeams",
  "largeBackground",
  "largeFakePixelSource"
];

describe("cleanup fixture catalog", () => {
  test("validates the M6.1 failure fixture intake metadata contract", () => {
    const validSingle = validateQualityFixtureMetadata({
      id: "m6-alpha-halo-bright-matte",
      sourceFilename: "synthetic://transparent-matte-halo/bright-matte",
      assetType: "sprite",
      expectedMode: "single",
      expectedTargetSize: { width: 64, height: 64 },
      failureCategories: ["bright-matte-halo"],
      desiredCleanupSettings: {
        alpha: "backgroundFloodFill",
        cleanup: { removeHalos: true, preserveSinglePixelDetails: true }
      },
      expectedWarnings: ["matte halo may require manual review"],
      reviewStatus: "report-only",
      privacy: {
        classification: "safe-to-commit",
        notes: "Synthetic first-party reproduction."
      },
      license: {
        provenance: "first-party-synthetic",
        notes: "Generated by deterministic fixture code."
      }
    });
    const invalidSheet = validateQualityFixtureMetadata({
      id: "Bad Sheet",
      sourceFilename: "",
      assetType: "animationSheet",
      expectedMode: "spriteSheet",
      failureCategories: [],
      reviewStatus: "golden-approved",
      privacy: {
        classification: "safe-to-commit",
        notes: ""
      },
      license: {
        provenance: "private-do-not-commit",
        notes: ""
      }
    });

    expect(qualityFixtureFailureCategories).toEqual(
      expect.arrayContaining([
        "bright-matte-halo",
        "noisy-pseudo-pixel-grid",
        "weak-ambiguous-grid",
        "uneven-row-sheet",
        "presentation-label-gutters",
        "palette-drift-animation",
        "outline-repair-failure"
      ])
    );
    expect(qualityFixtureReviewStatuses).toEqual(expect.arrayContaining(["report-only", "golden-approved", "needs-review", "internal-only"]));
    expect(validSingle).toEqual([]);
    expect(invalidSheet).toEqual(
      expect.arrayContaining([
        "id must be a lowercase slug",
        "sourceFilename is required",
        "failureCategories must include at least one category",
        "expectedSheetLayout is required for spriteSheet and tileSheet fixtures",
        "safe-to-commit fixtures cannot use private-do-not-commit license provenance",
        "privacy.notes is required",
        "license.notes is required"
      ])
    );
  });

  test("covers every MIG-6 cleanup category", () => {
    expect(cleanupFixtureCategories).toEqual(expectedCategories);
    expect(new Set([...cleanupFixtureCatalog.map((fixture) => fixture.category), ...benchmarkFixtureCatalog.map((fixture) => fixture.category)])).toEqual(
      new Set(expectedCategories)
    );
  });

  test("documents every fixture and uses MIG-5 taxonomy metadata", () => {
    const assetTypes = new Set(assetTypeDefinitions.map((definition) => definition.type));

    for (const fixture of cleanupFixtureCatalog) {
      expect(fixture.id).toMatch(/^[a-z0-9-]+$/);
      expect(fixture.description.length).toBeGreaterThan(12);
      expect(fixture.catches.length).toBeGreaterThan(0);
      expect(assetTypes.has(fixture.assetType)).toBe(true);
      expect(typeof fixture.createImage).toBe("function");
    }
  });

  test("includes expected named real-world cleanup cases", () => {
    expect(cleanupFixtureCatalog.map((fixture) => fixture.id)).toEqual(
      expect.arrayContaining([
        "single-robot-6x",
        "single-knight-8x-noisy",
        "ambiguous-grid-soft-block-sprite",
        "halo-transparent-edge",
        "matte-opaque-white-edge",
        "morphology-pinhole-orphan-sprite",
        "outline-repair-dual-tone",
        "palette-drift-walk-4f",
        "uneven-gutter-labeled-sheet",
        "drifted-effect-sheet",
        "baseline-drift-animation-sheet",
        "compact-nine-row-animation-sheet",
        "presentation-mockup-2x6-sheet",
        "tileset-seams-4x4-16",
        "tileset-broken-seams-2x2-16",
        "large-landscape-bands",
        "large-non-sprite-background"
      ])
    );
  });

  test("classifies the initial M6.1 quality failure fixture set", () => {
    const fixtureIds = new Set(cleanupFixtureCatalog.map((fixture) => fixture.id));
    const requiredFailureCategories = [
      "bright-matte-halo",
      "noisy-pseudo-pixel-grid",
      "weak-ambiguous-grid",
      "uneven-row-sheet",
      "presentation-label-gutters",
      "palette-drift-animation",
      "outline-repair-failure"
    ];

    for (const entry of qualityFailureFixtureCatalog) {
      expect(fixtureIds.has(entry.fixtureId)).toBe(true);
      expect(validateQualityFixtureMetadata(entry.metadata)).toEqual([]);
      expect(entry.metadata.sourceFilename).toMatch(/^synthetic:\/\//);
    }

    expect(qualityFailureFixtureCatalog.map((entry) => entry.fixtureId)).toEqual(
      expect.arrayContaining([
        "matte-opaque-white-edge",
        "single-knight-8x-noisy",
        "ambiguous-grid-soft-block-sprite",
        "uneven-gutter-labeled-sheet",
        "presentation-mockup-2x6-sheet",
        "palette-drift-walk-4f",
        "outline-repair-dual-tone"
      ])
    );
    expect([...new Set(qualityFailureFixtureCatalog.flatMap((entry) => entry.metadata.failureCategories))]).toEqual(
      expect.arrayContaining(requiredFailureCategories)
    );
    expect(qualityFailureFixtureCatalog.some((entry) => entry.metadata.reviewStatus === "report-only")).toBe(true);
  });

  test("includes both seamless and broken tileset seam fixtures", () => {
    const ids = cleanupFixtureCatalog.filter((fixture) => fixture.category === "tilesetSeams").map((fixture) => fixture.id);

    expect(ids).toContain("tileset-seams-4x4-16");
    expect(ids).toContain("tileset-broken-seams-2x2-16");
  });

  test("includes unstable animation sheet warning metadata", () => {
    const fixture = cleanupFixtureCatalog.find((candidate) => candidate.id === "baseline-drift-animation-sheet");
    const frames = fixture?.expected.sheet?.frames ?? [];

    expect(fixture).toBeDefined();
    expect(fixture?.expected.sheet?.options).toMatchObject({ frameWidth: 32, frameHeight: 32, rows: 1, columns: 4, margin: 2, spacing: 6 });
    expect(fixture?.expected.sheet?.rowFrameCounts).toEqual([4]);
    expect(fixture?.expected.sheet?.animationNames).toEqual(["walk_down"]);
    expect(fixture?.expected.sheet?.expectedWarnings).toEqual(["baseline-drift", "content-center-drift"]);
    expect(fixture?.createImage()).toMatchObject({ width: 160, height: 40 });
    expect(frames).toHaveLength(4);
    expect(new Set(frames.map((frame) => `${frame.rect.w}x${frame.rect.h}`))).toEqual(new Set(["32x32"]));
    expect(new Set(frames.map((frame) => frame.pivot.y)).size).toBeGreaterThan(1);
    expect(new Set(frames.map((frame) => `${frame.sourceRect?.x},${frame.sourceRect?.y}`)).size).toBeGreaterThan(1);
  });

  test("includes compact nine-row animation sheet metadata", () => {
    const fixture = cleanupFixtureCatalog.find((candidate) => candidate.id === "compact-nine-row-animation-sheet");

    expect(fixture).toBeDefined();
    expect(fixture?.category).toBe("unevenSpriteSheet");
    expect(fixture?.expected.sheet?.options).toMatchObject({ frameWidth: 55, frameHeight: 46, rows: 9, columns: 9, margin: 8, spacing: 0 });
    expect(fixture?.expected.sheet?.rowFrameCounts).toEqual([1, 8, 9, 5, 5, 8, 7, 4, 4]);
    expect(fixture?.expected.sheet?.animationNames).toEqual(["row_1", "row_2", "row_3", "row_4", "row_5", "row_6", "row_7", "row_8", "row_9"]);
    expect(fixture?.expected.sheet?.expectedWarnings).toEqual([
      "Rows contain different frame counts; rectangular sheet controls will include empty cells unless explicit frames are used.",
      "Detected variable-size compact animation frames; normalized export should use explicit source rectangles and bottom-middle pivots."
    ]);
    expect(fixture?.createImage()).toMatchObject({ width: 510, height: 510 });
  });

  test("includes presentation-style sheet fixture metadata", () => {
    const fixture = cleanupFixtureCatalog.find((candidate) => candidate.id === "presentation-mockup-2x6-sheet");
    const frames = fixture?.expected.sheet?.frames ?? [];

    expect(fixture).toBeDefined();
    expect(fixture?.category).toBe("presentationSpriteSheet");
    expect(fixture?.expected.sheet?.options).toMatchObject({ frameWidth: 96, frameHeight: 120, rows: 2, columns: 6, margin: 46, spacing: 8 });
    expect(fixture?.expected.sheet?.rowFrameCounts).toEqual([6, 6]);
    expect(fixture?.expected.sheet?.animationNames).toEqual(["run", "cast"]);
    expect(fixture?.expected.sheet?.expectedWarnings).toEqual(["presentation-sheet-artifacts", "baked-checkerboard-cells", "caption-bracket-ignored"]);
    expect(fixture?.createImage()).toMatchObject({ width: 720, height: 420 });
    expect(frames).toHaveLength(12);
    expect(new Set(frames.map((frame) => frame.tags?.[0]))).toEqual(new Set(["run", "cast"]));
    expect(frames.every((frame) => frame.sourceRect && frame.sourceRect.w < frame.rect.w && frame.sourceRect.h < frame.rect.h)).toBe(true);
  });

  test("keeps large benchmark sources lazy", () => {
    expect(benchmarkFixtureCatalog.map((fixture) => fixture.id)).toEqual([
      "fake-pixel-720p-single",
      "fake-pixel-1080p-single",
      "fake-pixel-large-sheet"
    ]);

    for (const fixture of benchmarkFixtureCatalog) {
      expect(fixture.sourcePixels).toBeGreaterThan(fixture.nativePixels);
      expect(typeof fixture.createImage).toBe("function");
    }
  });

  test("maps visual regression cases to existing fixtures and key categories", () => {
    const fixtureIds = new Set(cleanupFixtureCatalog.map((fixture) => fixture.id));
    const categories = new Set(visualRegressionCases.map((fixture) => fixture.category));

    for (const fixture of visualRegressionCases) {
      expect(fixtureIds.has(fixture.fixtureId)).toBe(true);
      expect(fixture.expected.checksum.length).toBeGreaterThan(0);
    }
    expect(categories).toEqual(new Set(["highResolutionPseudoPixelSprite", "transparentMatteHaloSprite", "paletteDriftAnimationFrames", "unevenSpriteSheet", "tilesetSeams"]));
  });
});
