import type { QualityFailureFixtureCatalogEntry } from "./types";

const firstPartySyntheticLicense = {
  provenance: "first-party-synthetic",
  notes: "Generated by deterministic fixture code in this repository."
} as const;

const safeSyntheticPrivacy = {
  classification: "safe-to-commit",
  notes: "Synthetic reproduction with no private user source material."
} as const;

export const qualityFailureFixtureCatalog: QualityFailureFixtureCatalogEntry[] = [
  {
    fixtureId: "matte-opaque-white-edge",
    reportOnly: false,
    metadata: {
      id: "m6-alpha-bright-matte-halo",
      sourceFilename: "synthetic://transparent-matte-halo/opaque-white-edge",
      assetType: "sprite",
      expectedMode: "single",
      expectedTargetSize: { width: 64, height: 64 },
      failureCategories: ["bright-matte-halo", "background-alpha-flood-fill"],
      desiredCleanupSettings: {
        alpha: "backgroundFloodFill",
        alphaSettings: { tolerance: 18, decontaminateRgb: true, transparentRgb: "#000000" },
        cleanup: { removeHalos: true, preserveSinglePixelDetails: true },
        maxColors: 8
      },
      expectedWarnings: ["bright matte may require alpha tolerance review"],
      reviewStatus: "golden-approved",
      privacy: safeSyntheticPrivacy,
      license: firstPartySyntheticLicense
    }
  },
  {
    fixtureId: "single-knight-8x-noisy",
    reportOnly: false,
    metadata: {
      id: "m6-grid-noisy-knight",
      sourceFilename: "synthetic://high-resolution-pseudo-pixel/noisy-knight-8x",
      assetType: "sprite",
      expectedMode: "single",
      expectedTargetSize: { width: 64, height: 80 },
      failureCategories: ["noisy-pseudo-pixel-grid"],
      desiredCleanupSettings: {
        downscale: "adaptive",
        grid: { detect: "auto", scaleX: 8, scaleY: 8 },
        cleanup: { preserveSinglePixelDetails: true },
        maxColors: 20
      },
      expectedWarnings: ["block color wobble should not create palette drift"],
      reviewStatus: "needs-review",
      privacy: safeSyntheticPrivacy,
      license: firstPartySyntheticLicense
    }
  },
  {
    fixtureId: "ambiguous-grid-soft-block-sprite",
    reportOnly: true,
    metadata: {
      id: "m6-grid-ambiguous-soft-block",
      sourceFilename: "synthetic://high-resolution-pseudo-pixel/ambiguous-soft-block-6x",
      assetType: "sprite",
      expectedMode: "single",
      expectedTargetSize: { width: 48, height: 48 },
      failureCategories: ["weak-ambiguous-grid"],
      desiredCleanupSettings: {
        grid: { detect: "auto", scaleX: 6, scaleY: 6 },
        downscale: "dominant",
        cleanup: { preserveSinglePixelDetails: true },
        maxColors: 16
      },
      expectedWarnings: ["low grid confidence should stay visible until manually confirmed"],
      reviewStatus: "report-only",
      privacy: safeSyntheticPrivacy,
      license: firstPartySyntheticLicense
    }
  },
  {
    fixtureId: "uneven-gutter-labeled-sheet",
    reportOnly: false,
    metadata: {
      id: "m6-sheet-uneven-row-gutters",
      sourceFilename: "synthetic://uneven-sprite-sheet/labeled-row-sheet",
      assetType: "animationSheet",
      expectedMode: "spriteSheet",
      expectedSheetLayout: { frameWidth: 48, frameHeight: 42, rows: 3, columns: 6, margin: 84, spacing: 0, rowFrameCounts: [4, 6, 5] },
      failureCategories: ["uneven-row-sheet", "sheet-detection-correction"],
      desiredCleanupSettings: {
        downscale: "detailPreserving",
        cleanup: { preserveSinglePixelDetails: true },
        maxColors: 32
      },
      expectedWarnings: ["Normalized uneven gutters from content centers; inspect frame boxes before export."],
      reviewStatus: "needs-review",
      privacy: safeSyntheticPrivacy,
      license: firstPartySyntheticLicense
    }
  },
  {
    fixtureId: "presentation-mockup-2x6-sheet",
    reportOnly: false,
    metadata: {
      id: "m6-sheet-presentation-label-gutters",
      sourceFilename: "synthetic://presentation-sprite-sheet/mockup-2x6",
      assetType: "animationSheet",
      expectedMode: "spriteSheet",
      expectedSheetLayout: { frameWidth: 96, frameHeight: 120, rows: 2, columns: 6, margin: 46, spacing: 8, rowFrameCounts: [6, 6] },
      failureCategories: ["presentation-label-gutters", "sheet-detection-correction"],
      desiredCleanupSettings: {
        downscale: "detailPreserving",
        cleanup: { preserveSinglePixelDetails: true },
        maxColors: 32
      },
      expectedWarnings: ["presentation-sheet-artifacts", "baked-checkerboard-cells", "caption-bracket-ignored"],
      reviewStatus: "needs-review",
      privacy: safeSyntheticPrivacy,
      license: firstPartySyntheticLicense
    }
  },
  {
    fixtureId: "palette-drift-walk-4f",
    reportOnly: false,
    metadata: {
      id: "m6-palette-drift-walk-cycle",
      sourceFilename: "synthetic://palette-drift/walk-cycle-4f",
      assetType: "animationSheet",
      expectedMode: "spriteSheet",
      expectedSheetLayout: { frameWidth: 24, frameHeight: 32, rows: 1, columns: 4, margin: 0, spacing: 0, rowFrameCounts: [4] },
      failureCategories: ["palette-drift-animation"],
      desiredCleanupSettings: {
        paletteSettings: { lockScope: "sheet", dithering: "none" },
        cleanup: { preserveSinglePixelDetails: true },
        maxColors: 12
      },
      expectedWarnings: ["frame-local palettes should remain inside the shared sheet palette"],
      reviewStatus: "golden-approved",
      privacy: safeSyntheticPrivacy,
      license: firstPartySyntheticLicense
    }
  },
  {
    fixtureId: "outline-repair-dual-tone",
    reportOnly: false,
    metadata: {
      id: "m6-outline-repair-dual-tone",
      sourceFilename: "synthetic://transparent-matte-halo/dual-tone-outline",
      assetType: "sprite",
      expectedMode: "single",
      expectedTargetSize: { width: 16, height: 16 },
      failureCategories: ["outline-repair-failure"],
      desiredCleanupSettings: {
        alpha: "preserve",
        cleanup: {
          outlineMode: "repairExisting",
          outlineSourceColors: ["#101112", "#183f3c"],
          preserveSinglePixelDetails: true
        },
        maxColors: 12
      },
      expectedWarnings: ["explicit outline source colors should survive repair and remap"],
      reviewStatus: "golden-approved",
      privacy: safeSyntheticPrivacy,
      license: firstPartySyntheticLicense
    }
  },
  {
    fixtureId: "morphology-pinhole-orphan-sprite",
    reportOnly: false,
    metadata: {
      id: "m6-morphology-pinhole-orphan",
      sourceFilename: "synthetic://transparent-matte-halo/morphology-pinhole-orphan",
      assetType: "sprite",
      expectedMode: "single",
      expectedTargetSize: { width: 12, height: 12 },
      failureCategories: ["morphology-artifact"],
      desiredCleanupSettings: {
        alpha: "preserve",
        cleanup: {
          morphology: {
            enabled: true,
            fillTinyHoles: true,
            removeTinyComponents: true,
            maxHolePixels: 1,
            maxComponentPixels: 1,
            preserveSinglePixelDetails: false
          }
        },
        maxColors: 6
      },
      expectedWarnings: ["morphology diagnostics should report filled holes and removed components"],
      reviewStatus: "golden-approved",
      privacy: safeSyntheticPrivacy,
      license: firstPartySyntheticLicense
    }
  }
];
